package com.cmolina12.flowplan_backend.controller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.cmolina12.flowplan_backend.service.ScheduleService; // Importing the ScheduleService to use its methods for generating schedules based on course sections.
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import com.cmolina12.flowplan_backend.domain.Section; // Importing the Section domain model to represent course sections in the schedule.
import java.util.List; // Importing List to handle collections of sections in the schedule.



@RestController
@RequestMapping("/api/schedule")
public class ScheduleController {

    // This controller handles requests related to schedule generation based on course sections.
    private final ScheduleService scheduleService; // scheduleService is an instance of ScheduleService, which is used to generate schedules based on course sections.
    
    /**
     * Constructor for ScheduleController.
     * 
     * @param scheduleService the ScheduleService instance used to generate schedules.
     */

    public ScheduleController(ScheduleService scheduleService) {
        this.scheduleService = scheduleService; // The ScheduleService instance is injected into the controller, allowing it to use the service methods to generate schedules.
    }

    /**
     * Generates all possible schedules based on the provided list of lists of Section objects.
     * 
     * @param candidates a list of lists of Section objects representing the course sections to consider for schedule generation.
     * @return a list of lists of Section objects representing all possible schedules generated by the ScheduleService.
     */
    
    @PostMapping
    public List<List<Section>> getSchedules(@RequestBody List<List<Section>> candidates) {
        return scheduleService.generateAllSchedules(candidates); // This method handles POST requests to /api/schedule, taking a list of lists of Section objects as input and returning all possible schedules generated by the ScheduleService.
    }
    
}
